[package]
name = "melt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
melt-rs = { path ="../melt-rs"}
druid = { git = "https://github.com/linebender/druid.git", features = ["im"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
uuid = { version = "1.2.2", features = ["serde", "v4"] }
clipboard = "0.5.0"
syntect = "5.0.0"