name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: windows-latest
            suffix: .exe
            target: x86_64-pc-windows-msvc
    name: build melt-${{ matrix.package }}-${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.settings.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: melt-${{ matrix.settings.target }}${{ matrix.settings.suffix }}
          path: ./target/release/melt${{ matrix.settings.suffix }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'melt*/*'
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}