name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package: [ web, deploy ]
        settings:
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: windows-latest
            suffix: .exe
            target: x86_64-pc-windows-msvc
    name: build melt-${{ matrix.package }}-${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.settings.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          directory: ./target/release
          path: melt-${{ matrix.package }}${{ matrix.settings.suffix }}
          filename: melt-${{ matrix.package }}-${{ matrix.settings.target }}.zip
      #      - name: Display structure of Upload files
      #        run: ls -R
      #      - name: Zip artifact
      #        run: zip -j melt-${{ matrix.package }}-${{ matrix.target }} ./target/release/melt-${{ matrix.package }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: melt-${{ matrix.package }}-${{ matrix.settings.target }}${{ matrix.settings.suffix }}
          path: ./target/release/melt-${{ matrix.package }}-${{ matrix.settings.target }}.zip
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
      #      - name: Display structure of downloaded files
      #        run: ls -R
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'melt-*/*.zip'
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}